apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3-be-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mhd1324/app3-backend-config.git
    targetRevision: HEAD
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: app3-ns